// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4915.MecanumDrive;
    
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.hal.CanTalonSRX;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.livewindow.LiveWindowSendable;

import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CanTalonSRX mecanumDriveControls1LeftFront1;
    public static CanTalonSRX mecanumDriveControls1LeftRear2;
    public static CanTalonSRX mecanumDriveControls1RightFront3;
    public static CanTalonSRX mecanumDriveControls1RightRear4;
    public static RobotDrive mecanumDriveControls1RobotDrive41;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
    	mecanumDriveControls1LeftFront1 = new CanTalonSRX(10); 
    	mecanumDriveControls1LeftRear2 = new CanTalonSRX(11);
    	mecanumDriveControls1RightFront3 = new CanTalonSRX(12);
    	mecanumDriveControls1RightRear4 = new CanTalonSRX(13);
    	
    	
    	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        
        LiveWindow.addActuator("Mecanum Drive Controls 1", "Left Front 1", (LiveWindowSendable) mecanumDriveControls1LeftFront1);
        
       
        LiveWindow.addActuator("Mecanum Drive Controls 1", "Left Rear 2", (LiveWindowSendable) mecanumDriveControls1LeftRear2);
        
       
        LiveWindow.addActuator("Mecanum Drive Controls 1", "Right Front 3", (LiveWindowSendable) mecanumDriveControls1RightFront3);
        
        
        LiveWindow.addActuator("Mecanum Drive Controls 1", "Right Rear 4", (LiveWindowSendable) mecanumDriveControls1RightRear4);
        
        mecanumDriveControls1RobotDrive41 = new RobotDrive(mecanumDriveControls1LeftFront1, mecanumDriveControls1LeftRear2,
              mecanumDriveControls1RightFront3, mecanumDriveControls1RightRear4);
        
        mecanumDriveControls1RobotDrive41.setSafetyEnabled(true);
        mecanumDriveControls1RobotDrive41.setExpiration(0.1);
        mecanumDriveControls1RobotDrive41.setSensitivity(0.5);
        mecanumDriveControls1RobotDrive41.setMaxOutput(1.0);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
