// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc4915.MecanumDrive.commands;

import java.util.ArrayList;
import java.util.List;

import org.usfirst.frc4915.MecanumDrive.Robot;
import org.usfirst.frc4915.MecanumDrive.subsystems.DriveTrain;

import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.command.Command;

public class MoveStraightPositionModeCommand extends Command {
	public static List<CANTalon> motors = DriveTrain.motors;
	public double inputDistance;
	private DriveTrain driveTrain = Robot.driveTrain;

	public MoveStraightPositionModeCommand(double inputDistance) {
		requires(driveTrain);
		System.out.println("***MoveStraightPositionModeCommand inputDistance: " + inputDistance + "*******");
		this.inputDistance = inputDistance;
		// Use requires() here to declare subsystem dependencies
		// eg. requires(chassis);
	}

	private List<Double> desiredTicksValue;

	// Called just before this Command runs the first time
	/**
	 * This initializes the variables for the distance calculator.
	 */
	protected void initialize() {
		desiredTicksValue = new ArrayList<Double>();

		double ticksToMove = inputDistance * 12 * 1000 / (6 * Math.PI);

		System.out.println("Input distance: " + inputDistance + " ft, ticks to move: " + ticksToMove);

		for (int i = 0; i < motors.size(); i++) {
			CANTalon motor = motors.get(i);

			double startingTickValue = motor.getPosition();
			Double endValue = startingTickValue + ticksToMove;
			if (i >= 2) {
				// right motors are inverted
				endValue = startingTickValue - ticksToMove;
			}

			System.out.println("Motor " + i + ": starting position " + startingTickValue + ", desired position " + endValue);
			desiredTicksValue.add(endValue);
		}
	}

	/**
	 * This uses the wheel circumference and the number of rotations to compute
	 * the distance traveled.
	 */

	// Called repeatedly when this Command is scheduled to run
	protected void execute() {
		if (inputDistance < 0)
			driveTrain.driveStraight(0.7);
		else
			driveTrain.driveStraight(-0.7);
	}

	// Make this return true when this Command no longer needs to run execute()
	protected boolean isFinished() {
		// checking to see if the front motors have finished regardless of driving direction
		if (inputDistance > 0)
			return isMotorFinished(0) || isMotorFinished(2);
		else
			return isMotorFinished(1) || isMotorFinished(3);
	}
	private boolean isMotorFinished(int i) {
		boolean finished = false;
		double currentPosition = motors.get(i).getPosition();
		Double desiredPosition = desiredTicksValue.get(i);
		System.out.println("Motor " + i + ": current position: " + currentPosition + ", desired position " + desiredPosition);

		if (i >= 2) {
			// right motors are inverted
			if (inputDistance < 0) {
				finished = currentPosition >= desiredPosition;
			} else {
				finished = currentPosition <= desiredPosition;
			}
		} else {
			if (inputDistance < 0) {
				finished = currentPosition <= desiredPosition;
			} else {
				finished = currentPosition >= desiredPosition;
			}
		}
		return finished;

	}
	// Called once after isFinished returns true
	protected void end() {
		System.out.println("Stopping motor");
		driveTrain.getRobotDrive().stopMotor();
	}

	// Called when another command which requires one or more of the same
	// subsystems is scheduled to run
	protected void interrupted() {
		System.out.println("Command interrupted!");
		end();
	}
}
